/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Form;

import db.Config;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Locale;

/**
 *
 * @author HP
 */
public class FPembayaran extends javax.swing.JInternalFrame {
    
    java.util.Date tglsekarang = new java.util.Date();
    private final SimpleDateFormat smpdtfmt = new SimpleDateFormat("yyyy/MM/dd", Locale.getDefault());
    //diatas adalah pengaturan format penulisan, bisa diubah sesuai keinginan.
    private final String tanggal = smpdtfmt.format(tglsekarang);
    
    /**
     * Creates new form FTransaksi
     */
    public FPembayaran() {
        initComponents();
        tampilTransaksi();
    }
    
    public void tampilTransaksi() {        
        
        try {            
        //connect ke db
            Connection conn = (Connection) Config.configDB();
            
            //buka query
            Statement st = conn.createStatement();
            
            //query sql
            String sql = "SELECT id_transaksi from transaksi WHERE keterangan != 'LUNAS' ORDER BY id_transaksi ASC";
            
            //exce
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                Object[] ob = new Object[1];
                ob[0] = rs.getString("id_transaksi");
                cbTransaksi.addItem((String)ob[0]);
            }
            
            rs.close();
            st.close();
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error : "+e);
        }
        
    }
    
    public void clearComponents() {
        txtIdb.setText("");
        txtIdp.setText("");
        txtNamab.setText("");
        txtHargab.setText("");
        txtNamap.setText("");
        cbTransaksi.removeAllItems();
    }
    
    public void tampilData(){
        try{
            //connect ke db
            Connection conn = (Connection) Config.configDB();
            
            //buka query
            Statement st = conn.createStatement();
            
            //query sql
            String sql = "SELECT t.id_transaksi, t.id_barang, t.id_pembeli, t.tanggal, t.keterangan, p.nama_pembeli,"
            + "b.nama_barang, b.harga FROM transaksi as t JOIN barang as b JOIN pembeli as p WHERE "
            + "t.id_barang = b.id_barang AND t.id_pembeli = p.id_pembeli AND t.id_transaksi = "+cbTransaksi.getSelectedItem();
            
            //exce
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                Object[] ob = new Object[5];
                ob[0] = rs.getString("id_barang");
                ob[1] = rs.getString("nama_barang");
                ob[2] = rs.getString("harga");
                ob[3] = rs.getString("id_pembeli");
                ob[4] = rs.getString("nama_pembeli");
                
                //set data ke text field
                txtIdb.setText((String) ob[0]);
                txtNamab.setText((String) ob[1]);
                txtHargab.setText((String) ob[2]);
                txtIdp.setText((String) ob[3]);
                txtNamap.setText((String) ob[4]);
            }
            
            rs.close();
            st.close();
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error : "+e);
        }
    }

    public void confirmPembayaran(){
        try { 
            
            Connection conn = (Connection) Config.configDB();
            Statement st = conn.createStatement();
            String sql = "insert into pembayaran(tgl_bayar, total_bayar, id_transaksi) values ('"+tanggal+"',"+txtHargab.getText()+","+cbTransaksi.getSelectedItem()+")";
            String sql2 = "update transaksi set keterangan='LUNAS' where id_transaksi = "+cbTransaksi.getSelectedItem();
            st.executeUpdate(sql);
            st.executeUpdate(sql2);
            JOptionPane.showMessageDialog(null, "Transaksi sudah dikonfirmasi!");
            clearComponents();
            st.close();                              
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null, "Error : "+e); 
        } 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblConfirm = new javax.swing.JButton();
        txtIdb = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHargab = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNamab = new javax.swing.JTextField();
        txtIdp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNamap = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbTransaksi = new javax.swing.JComboBox();
        tblRefresh = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        tblConfirm.setText("Konfirmasi");
        tblConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblConfirmActionPerformed(evt);
            }
        });

        jLabel3.setText("ID Barang");

        jLabel4.setText("Harga");

        jLabel5.setText("ID Pembeli");

        jLabel6.setText("Nama Barang");

        jLabel7.setText("Nama Pembeli");

        jLabel8.setText("ID Transaksi");

        cbTransaksi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih ID" }));
        cbTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTransaksiActionPerformed(evt);
            }
        });

        tblRefresh.setText("Refresh");
        tblRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblRefreshActionPerformed(evt);
            }
        });

        jPanel13.setBackground(new java.awt.Color(69, 123, 157));

        jPanel14.setBackground(new java.awt.Color(241, 250, 238));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jLabel9.setBackground(new java.awt.Color(241, 250, 238));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(241, 250, 238));
        jLabel9.setText("FORM PEMBAYARAN");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(107, 107, 107))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(30, 30, 30)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(230, 57, 70));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtIdp)
                                .addGap(57, 57, 57))
                            .addComponent(txtNamab)
                            .addComponent(txtHargab)
                            .addComponent(txtNamap, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdb, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(tblConfirm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tblRefresh)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNamab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHargab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNamap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtIdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tblConfirm)
                    .addComponent(tblRefresh))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblConfirmActionPerformed
        // TODO add your handling code here:    
        if(cbTransaksi.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "ID Transaksi tidak boleh kosong!");
        } else if(txtIdb.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "ID Barang tidak boleh kosong!");
        } else if (!txtIdb.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "ID Barang hanya berupa angka!");
        } else if(txtIdp.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "ID Pembeli tidak boleh kosong!");
        } else if (!txtIdp.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "ID Pembeli hanya berupa angka!");
        } else if (txtNamab.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama Barang tidak boleh kosong!");
        } else if (txtHargab.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harga Barang tidak boleh kosong!");
        } else if (!txtHargab.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "Harga Barang hanya berupa angka!");
        } else if (txtNamap.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama Pembeli tidak boleh kosong!");
        } else {
            int val = JOptionPane.showConfirmDialog(null, "Konfirmasi pembayaran?", "", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);

            if(val == JOptionPane.YES_OPTION){
                confirmPembayaran();            
            }            
        }
    }//GEN-LAST:event_tblConfirmActionPerformed

    private void cbTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTransaksiActionPerformed
        // TODO add your handling code here:
        tampilData();
    }//GEN-LAST:event_cbTransaksiActionPerformed

    private void tblRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblRefreshActionPerformed
        // TODO add your handling code here:
        clearComponents();
        tampilTransaksi();
    }//GEN-LAST:event_tblRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbTransaksi;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton tblConfirm;
    private javax.swing.JButton tblRefresh;
    private javax.swing.JTextField txtHargab;
    private javax.swing.JTextField txtIdb;
    private javax.swing.JTextField txtIdp;
    private javax.swing.JTextField txtNamab;
    private javax.swing.JTextField txtNamap;
    // End of variables declaration//GEN-END:variables
}
