/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Form;

import db.Config;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.plaf.ComponentUI;

/**
 *
 * @author HP
 */
public class FTambahSupplier extends javax.swing.JInternalFrame {

    /**
     * Creates new form FTambahSupplier
     */
    public FTambahSupplier() {
        initComponents();
    }

    public void clearComponents() {
        txtNamas.setText("");
        txtNos.setText("");
        txtAlamats.setText("");
    }
    
    public void tambahSupplier() {
        try {
            //conect
            Connection conn = (Connection) Config.configDB();
            
            //state
            Statement state = conn.createStatement();
            
            //query
            String sql = "INSERT INTO supplier(nama_supplier, no_telp, alamat) VALUES('"+ txtNamas.getText() +"','" + txtNos.getText() + ""
                    + "', '"+ txtAlamats.getText() +"')";
            state.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");
            clearComponents();
            state.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error : " + e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNos = new javax.swing.JTextField();
        txtNamas = new javax.swing.JTextField();
        txtAlamats = new javax.swing.JTextField();
        tblResets = new javax.swing.JButton();
        tblSumbits = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("TAMBAH SUPPLIER");

        jLabel2.setText("Nama Supplier");

        jLabel3.setText("No Telepon");

        jLabel4.setText("Alamat");

        tblResets.setText("Reset");
        tblResets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblResetsActionPerformed(evt);
            }
        });

        tblSumbits.setText("Submit");
        tblSumbits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblSumbitsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAlamats, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(tblResets)
                        .addGap(18, 18, 18)
                        .addComponent(tblSumbits)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlamats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblResets)
                    .addComponent(tblSumbits))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblResetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblResetsActionPerformed
        // TODO add your handling code here:
        clearComponents();
    }//GEN-LAST:event_tblResetsActionPerformed

    private void tblSumbitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblSumbitsActionPerformed
        // TODO add your handling code here:
        if (txtNamas.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama Pembeli tidak boleh kosong!");
        } else if (txtNos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No Telepon tidak boleh kosong!");
        } else if (!txtNos.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "No Telepon hanya berupa angka!");
        } else if (txtAlamats.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih salah satu Supplier!");
        } else {
            tambahSupplier();
        }
    }//GEN-LAST:event_tblSumbitsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton tblResets;
    private javax.swing.JButton tblSumbits;
    private javax.swing.JTextField txtAlamats;
    private javax.swing.JTextField txtNamas;
    private javax.swing.JTextField txtNos;
    // End of variables declaration//GEN-END:variables
}
