/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Form;

import db.Config;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.plaf.ComponentUI;




/**
 *
 * @author HP
 */
public class FTambahBarang extends javax.swing.JInternalFrame {

    /**
     * Creates new form FTambahBarang
     */
    public FTambahBarang() {
        initComponents();
        tampilSupplier();
    }
    
    public void clearComponents() {
        txtNamab.setText("");
        txtHargab.setText("");
        txtStokb.setText("");
    }
    
        public void Validasi() {
        txtNamab.setUI(new JTextFieldHintUI("Masukan Nama..", Color.GRAY));
        txtHargab.setUI(new JTextFieldHintUI("Masukan Harga..", Color.GRAY));
        txtStokb.setUI(new JTextFieldHintUI("Masukan Stok..", Color.GRAY));
    }
    
    public void tambahBarang() {
        try {
            //conect
            Connection conn = (Connection) Config.configDB();
            
            //state
            Statement state = conn.createStatement();
            
            //query
            String sql = "INSERT INTO barang(nama_barang, harga, stok, id_supplier) VALUES('"+ txtNamab.getText() +"', '" + txtHargab.getText() + ""
                    + "', '"+ txtStokb.getText() +"','"+ cbSupplierb.getSelectedIndex() +"')";
            state.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");
            clearComponents();
            state.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error : " + e);
        }
    }
    
    public void tampilSupplier() {        
        
        try {            
        //connect ke db
            Connection conn = (Connection) Config.configDB();
            
            //buka query
            Statement st = conn.createStatement();
            
            //query sql
            String sql = "SELECT nama_supplier from supplier ORDER BY nama_supplier ASC";
            
            //exce
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                Object[] ob = new Object[1];
                ob[0] = rs.getString("nama_supplier");
                cbSupplierb.addItem((String)ob[0]);
            }
            
            rs.close();
            st.close();
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error : "+e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNamab = new javax.swing.JTextField();
        txtHargab = new javax.swing.JTextField();
        txtStokb = new javax.swing.JTextField();
        cbSupplierb = new javax.swing.JComboBox();
        tblSubmitb = new javax.swing.JButton();
        tblResetB = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("TAMBAH BARANG");

        jLabel3.setText("Nama Barang");

        jLabel4.setText("Harga");

        jLabel5.setText("Stok");

        jLabel6.setText("Supplier");

        cbSupplierb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Supplier" }));

        tblSubmitb.setText("Submit");
        tblSubmitb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblSubmitbActionPerformed(evt);
            }
        });

        tblResetB.setText("Reset");
        tblResetB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblResetBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tblResetB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tblSubmitb)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(142, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHargab, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamab, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStokb, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSupplierb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtNamab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtHargab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtStokb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cbSupplierb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblSubmitb)
                    .addComponent(tblResetB))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblResetBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblResetBActionPerformed
        // TODO add your handling code here:
        clearComponents();
    }//GEN-LAST:event_tblResetBActionPerformed

    private void tblSubmitbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblSubmitbActionPerformed
        // TODO add your handling code here:
        if (txtNamab.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama Barang tidak boleh kosong!");
        } else if (txtHargab.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harga tidak boleh kosong!");
        } else if (!txtHargab.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "Harga hanya berupa angka!");
        } else if (txtStokb.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Stok tidak boleh kosong!");
        } else if (!txtStokb.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "Stok hanya berupa angka!");
        } else if (cbSupplierb.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Pilih salah satu Supplier!");
        } else {
           tambahBarang();
        } 
    }//GEN-LAST:event_tblSubmitbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbSupplierb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton tblResetB;
    private javax.swing.JButton tblSubmitb;
    private javax.swing.JTextField txtHargab;
    private javax.swing.JTextField txtNamab;
    private javax.swing.JTextField txtStokb;
    // End of variables declaration//GEN-END:variables
}
