/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Form;

import db.Config;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Locale;

/**
 *
 * @author HP
 */
public class FTransaksi extends javax.swing.JInternalFrame {
    
    java.util.Date tglsekarang = new java.util.Date();
    private final SimpleDateFormat smpdtfmt = new SimpleDateFormat("yyyy/MM/dd", Locale.getDefault());
    //diatas adalah pengaturan format penulisan, bisa diubah sesuai keinginan.
    private final String tanggal = smpdtfmt.format(tglsekarang);
    
    /**
     * Creates new form FTransaksi
     */
    public FTransaksi() {
        initComponents();
        tabel();
    }
    
    public void clearComponents() {
        txtIdt.setText("");
        txtIdb.setText("");
        txtIdp.setText("");
        txtNamab.setText("");
        txtHargab.setText("");
        txtNamap.setText("");
    }
    
    private void tabel(){ 
    DefaultTableModel t= new DefaultTableModel();
    t.addColumn("ID Transaksi");
    t.addColumn("Nama Barang");   
    t.addColumn("Tanggal");
    t.addColumn("Harga");
    t.addColumn("Nama Pembeli");
    t.addColumn("Keterangan");
     tabelTransaksi.setModel(t); 
 
 try { 
    //conect
    Connection conn = (Connection) Config.configDB();
    
    //query sql
    String sql = "SELECT t.id_transaksi, t.tanggal, t.keterangan, p.nama_pembeli,"
            + "b.nama_barang, b.harga FROM transaksi as t JOIN barang as b JOIN pembeli as p WHERE "
            + "t.id_barang = b.id_barang AND t.id_pembeli = p.id_pembeli ORDER BY t.id_transaksi ASC";

    Statement st = conn.createStatement();
    
    //exce
    ResultSet rs = st.executeQuery(sql);
    rs = st.executeQuery(sql);
     while (rs.next()) { 
        t.addRow(new Object[]{ 
            rs.getString("id_transaksi"),
            rs.getString("nama_barang"),   
            rs.getString("tanggal"), 
            rs.getString("harga"),    
            rs.getString("nama_pembeli"),
            rs.getString("keterangan"),
        }); 
    }
     rs.close();
     st.close();
    }catch (Exception e) { 
    JOptionPane.showMessageDialog(null,"Error : "+e); 
    } 
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        tblTambah = new javax.swing.JButton();
        tblEdit = new javax.swing.JButton();
        tblHapus = new javax.swing.JButton();
        txtIdt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tblCari = new javax.swing.JButton();
        txtIdb = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHargab = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tblCarib = new javax.swing.JButton();
        txtNamab = new javax.swing.JTextField();
        txtIdp = new javax.swing.JTextField();
        tblCarip = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNamap = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("TRANSAKSI");

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelTransaksi);

        tblTambah.setText("Tambah");
        tblTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblTambahActionPerformed(evt);
            }
        });

        tblEdit.setText("Edit");
        tblEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblEditActionPerformed(evt);
            }
        });

        tblHapus.setText("Hapus");
        tblHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblHapusActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Transaksi");

        tblCari.setText("Cari");
        tblCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblCariActionPerformed(evt);
            }
        });

        jLabel3.setText("ID Barang");

        jLabel4.setText("Harga");

        jLabel5.setText("ID Pembeli");

        jLabel6.setText("Nama Barang");

        tblCarib.setText("Cari");
        tblCarib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblCaribActionPerformed(evt);
            }
        });

        tblCarip.setText("Cari");
        tblCarip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblCaripActionPerformed(evt);
            }
        });

        jLabel7.setText("Nama Pembeli");

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtIdp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tblCarip))
                                    .addComponent(txtNamab)
                                    .addComponent(txtHargab)
                                    .addComponent(txtNamap, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtIdt, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtIdb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tblCarib)
                                            .addComponent(tblCari)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tblTambah)
                                .addGap(18, 18, 18)
                                .addComponent(tblEdit)
                                .addGap(18, 18, 18)
                                .addComponent(tblHapus)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tblCarib))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNamab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHargab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNamap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tblTambah)
                            .addComponent(tblEdit)
                            .addComponent(tblHapus)
                            .addComponent(jButton1)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tblCarip)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblCariActionPerformed
        // TODO add your handling code here:
        try { 
            Connection conn = (Connection) Config.configDB();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select * from transaksi where "+ "id_transaksi='" +txtIdt.getText()
            +"'" ); 
            while (rs.next()) { 
                txtIdb.setText(rs.getString("id_transaksi")); 
                txtIdp.setText(rs.getString("id_pembeli"));
                }                                        
        } catch (Exception e) { 
        JOptionPane.showMessageDialog(null, "Error : "+e); 
        } 
    }//GEN-LAST:event_tblCariActionPerformed

    private void tblCaribActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblCaribActionPerformed
        // TODO add your handling code here:
        try { 
            Connection conn = (Connection) Config.configDB();
            Statement st = conn.createStatement();
            ResultSet rs=st.executeQuery("select * from barang where "+ "id_barang='" +txtIdb.getText()
            +"'" ); 
            while (rs.next()) { 
                txtNamab.setText(rs.getString("nama_barang")); 
                txtHargab.setText(rs.getString("harga"));
                }                                        
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null, "Error : "+e); 
        } 
    }//GEN-LAST:event_tblCaribActionPerformed

    private void tblCaripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblCaripActionPerformed
        // TODO add your handling code here:
        try { 
            Connection conn = (Connection) Config.configDB();
            Statement st = conn.createStatement();
            ResultSet rs=st.executeQuery("select * from pembeli where "+ "id_pembeli='" +txtIdp.getText()
            +"'" ); 
            while (rs.next()) { 
                txtNamap.setText(rs.getString("nama_pembeli"));
                }                                        
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null, "Error : "+e); 
        } 
    }//GEN-LAST:event_tblCaripActionPerformed

    private void tblTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblTambahActionPerformed
        // TODO add your handling code here:
        
        try { 
            
            Connection conn = (Connection) Config.configDB();
            Statement st = conn.createStatement();
            String sql = "insert into transaksi(id_barang, id_pembeli, tanggal, keterangan) values (" + txtIdb.getText() + "," + txtIdp.getText() + ",'" + tanggal + "','Belum Lunas')";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");
            clearComponents();
            st.close();                              
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null, "Error : "+e); 
        } 
    }//GEN-LAST:event_tblTambahActionPerformed

    private void tblEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblEditActionPerformed
        // TODO add your handling code here:
        try {            
            Connection conn = (Connection) Config.configDB();
            Statement st = conn.createStatement();
            String sql = "update transaksi set id_barang = '" + txtIdb.getText() + "', id_pembeli = '" + txtIdp.getText() + "'"
                    + "where id_transaksi = '" + txtIdt.getText() + "'";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data berhasil diupdate!");
            clearComponents();
            st.close();                              
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null, "Error : "+e); 
        } 
    }//GEN-LAST:event_tblEditActionPerformed

    private void tblHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblHapusActionPerformed
        // TODO add your handling code here:
        try { 
            
            Connection conn = (Connection) Config.configDB();
            Statement st = conn.createStatement();
            String sql = "delete from transaksi where id_transaksi = " + txtIdt.getText();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
            clearComponents();
            st.close();                              
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null, "Error : "+e); 
        } 
    }//GEN-LAST:event_tblHapusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tabel();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JButton tblCari;
    private javax.swing.JButton tblCarib;
    private javax.swing.JButton tblCarip;
    private javax.swing.JButton tblEdit;
    private javax.swing.JButton tblHapus;
    private javax.swing.JButton tblTambah;
    private javax.swing.JTextField txtHargab;
    private javax.swing.JTextField txtIdb;
    private javax.swing.JTextField txtIdp;
    private javax.swing.JTextField txtIdt;
    private javax.swing.JTextField txtNamab;
    private javax.swing.JTextField txtNamap;
    // End of variables declaration//GEN-END:variables
}
