
import Form.FPembayaran;
import Form.FTambahBarang;
import Form.FTambahPembeli;
import Form.FTambahSupplier;
import Form.FTransaksi;
import data.FLihatBarang;
import data.FLihatPembayaran;
import data.FLihatPembeli;
import data.FLihatSupplier;
import data.FLihatTransaksi;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author HP
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("Gambar/gb.jpg"));
        final Image img = icon.getImage();
        panelUtama = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g) {
                g.drawImage(img ,0 ,0 ,getWidth(), getHeight(), this);
            }
        };
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuTambahBarang = new javax.swing.JMenuItem();
        menuTambahPembeli = new javax.swing.JMenuItem();
        menuTambahSupplier = new javax.swing.JMenuItem();
        menuTambahTransaksi = new javax.swing.JMenuItem();
        menuTambahPembayaran = new javax.swing.JMenuItem();
        menuSupplier = new javax.swing.JMenu();
        dataBarang = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        dataPembeli = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        dataTransaksi = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        dataPembayaran = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        dataSupplier = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("TRANSAKSI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addGap(435, 435, 435)
                .addComponent(jButton1)
                .addContainerGap(476, Short.MAX_VALUE))
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(jButton1)
                .addContainerGap(332, Short.MAX_VALUE))
        );
        panelUtama.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu2.setText("Form");

        menuTambahBarang.setText("Tambah Data Barang");
        menuTambahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTambahBarangActionPerformed(evt);
            }
        });
        jMenu2.add(menuTambahBarang);

        menuTambahPembeli.setText("Tambah Data Pembeli");
        menuTambahPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTambahPembeliActionPerformed(evt);
            }
        });
        jMenu2.add(menuTambahPembeli);

        menuTambahSupplier.setText("Tambah Data Supplier");
        menuTambahSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTambahSupplierActionPerformed(evt);
            }
        });
        jMenu2.add(menuTambahSupplier);

        menuTambahTransaksi.setText("Tambah Data Transaksi");
        menuTambahTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTambahTransaksiActionPerformed(evt);
            }
        });
        jMenu2.add(menuTambahTransaksi);

        menuTambahPembayaran.setText("Tambah Data Pembayaran");
        menuTambahPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTambahPembayaranActionPerformed(evt);
            }
        });
        jMenu2.add(menuTambahPembayaran);

        jMenuBar1.add(jMenu2);

        menuSupplier.setText("Data");

        dataBarang.setText("Barang");
        dataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataBarangActionPerformed(evt);
            }
        });
        menuSupplier.add(dataBarang);
        menuSupplier.add(jSeparator2);

        dataPembeli.setText("Pembeli");
        dataPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataPembeliActionPerformed(evt);
            }
        });
        menuSupplier.add(dataPembeli);
        menuSupplier.add(jSeparator1);

        dataTransaksi.setText("Transaksi");
        dataTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataTransaksiActionPerformed(evt);
            }
        });
        menuSupplier.add(dataTransaksi);
        menuSupplier.add(jSeparator3);

        dataPembayaran.setText("Pembayaran");
        dataPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataPembayaranActionPerformed(evt);
            }
        });
        menuSupplier.add(dataPembayaran);
        menuSupplier.add(jSeparator4);

        dataSupplier.setText("Supplier");
        dataSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataSupplierActionPerformed(evt);
            }
        });
        menuSupplier.add(dataSupplier);

        jMenuBar1.add(menuSupplier);

        jMenu3.setText("About");

        jMenuItem2.setText("Made with <3 by Mart Team Provis 6");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuTambahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTambahBarangActionPerformed
        // TODO add your handling code here:
        panelUtama.removeAll();
        panelUtama.repaint();
        FTambahBarang tbh = new FTambahBarang();
        
        //size screen
        Dimension layarUtama = this.getSize();
        Dimension layarTbh = tbh.getSize();
        
        //simpan posisi frame ke tengah
        tbh.setLocation(layarUtama.width/2-layarTbh.width/2,layarUtama.height/2-layarTbh.height/2);
        
        panelUtama.add(tbh);
        tbh.setVisible(true);
    }//GEN-LAST:event_menuTambahBarangActionPerformed

    private void dataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataBarangActionPerformed
        // TODO add your handling code here:
        panelUtama.removeAll();
        panelUtama.repaint();
        FLihatBarang brg = new FLihatBarang();
        
        //size screen
        Dimension layarUtama = this.getSize();
        Dimension layarTbh = brg.getSize();
        
        //simpan posisi frame ke tengah
        brg.setLocation(layarUtama.width/2-layarTbh.width/2,layarUtama.height/2-layarTbh.height/2);
        
        panelUtama.add(brg);
        brg.setVisible(true);
    }//GEN-LAST:event_dataBarangActionPerformed

    private void menuTambahPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTambahPembeliActionPerformed
        // TODO add your handling code here:
        panelUtama.removeAll();
        panelUtama.repaint();
        FTambahPembeli pbl = new FTambahPembeli();
        
        //size screen
        Dimension layarUtama = this.getSize();
        Dimension layarTbh = pbl.getSize();
        
        //simpan posisi frame ke tengah
        pbl.setLocation(layarUtama.width/2-layarTbh.width/2,layarUtama.height/2-layarTbh.height/2);
        
        panelUtama.add(pbl);
        pbl.setVisible(true);
    }//GEN-LAST:event_menuTambahPembeliActionPerformed

    private void menuTambahSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTambahSupplierActionPerformed
        // TODO add your handling code here:
        panelUtama.removeAll();
        panelUtama.repaint();
        FTambahSupplier spl = new FTambahSupplier();
        
        //size screen
        Dimension layarUtama = this.getSize();
        Dimension layarTbh = spl.getSize();
        
        //simpan posisi frame ke tengah
        spl.setLocation(layarUtama.width/2-layarTbh.width/2,layarUtama.height/2-layarTbh.height/2);
        
        panelUtama.add(spl);
        spl.setVisible(true);
    }//GEN-LAST:event_menuTambahSupplierActionPerformed

    private void dataPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataPembeliActionPerformed
        // TODO add your handling code here: 
        panelUtama.removeAll();
        panelUtama.repaint();
        FLihatPembeli spl = new FLihatPembeli();
        
        //size screen
        Dimension layarUtama = this.getSize();
        Dimension layarTbh = spl.getSize();
        
        //simpan posisi frame ke tengah
        spl.setLocation(layarUtama.width/2-layarTbh.width/2,layarUtama.height/2-layarTbh.height/2);
        
        panelUtama.add(spl);
        spl.setVisible(true);
    }//GEN-LAST:event_dataPembeliActionPerformed

    private void dataSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataSupplierActionPerformed
        // TODO add your handling code here:
        panelUtama.removeAll();
        panelUtama.repaint();
        FLihatSupplier spl = new FLihatSupplier();
        
        //size screen
        Dimension layarUtama = this.getSize();
        Dimension layarTbh = spl.getSize();
        
        //simpan posisi frame ke tengah
        spl.setLocation(layarUtama.width/2-layarTbh.width/2,layarUtama.height/2-layarTbh.height/2);
        
        panelUtama.add(spl);
        spl.setVisible(true);
    }//GEN-LAST:event_dataSupplierActionPerformed

    private void dataPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataPembayaranActionPerformed
        // TODO add your handling code here:
        panelUtama.removeAll();
        panelUtama.repaint();
        FLihatPembayaran spl = new FLihatPembayaran();
        
        //size screen
        Dimension layarUtama = this.getSize();
        Dimension layarTbh = spl.getSize();
        
        //simpan posisi frame ke tengah
        spl.setLocation(layarUtama.width/2-layarTbh.width/2,layarUtama.height/2-layarTbh.height/2);
        
        panelUtama.add(spl);
        spl.setVisible(true);
    }//GEN-LAST:event_dataPembayaranActionPerformed

    private void dataTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataTransaksiActionPerformed
        // TODO add your handling code here:
        panelUtama.removeAll();
        panelUtama.repaint();
        FLihatTransaksi spl = new FLihatTransaksi();
        
        //size screen
        Dimension layarUtama = this.getSize();
        Dimension layarTbh = spl.getSize();
        
        //simpan posisi frame ke tengah
        spl.setLocation(layarUtama.width/2-layarTbh.width/2,layarUtama.height/2-layarTbh.height/2);
        
        panelUtama.add(spl);
        spl.setVisible(true);
    }//GEN-LAST:event_dataTransaksiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void menuTambahTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTambahTransaksiActionPerformed
        // TODO add your handling code here:
        panelUtama.removeAll();
        panelUtama.repaint();
        FTransaksi spl = new FTransaksi();
        
        //size screen
        Dimension layarUtama = this.getSize();
        Dimension layarTbh = spl.getSize();
        
        //simpan posisi frame ke tengah
        spl.setLocation(layarUtama.width/2-layarTbh.width/2,layarUtama.height/2-layarTbh.height/2);
        
        panelUtama.add(spl);
        spl.setVisible(true);
    }//GEN-LAST:event_menuTambahTransaksiActionPerformed

    private void menuTambahPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTambahPembayaranActionPerformed
        // TODO add your handling code here:
        panelUtama.removeAll();
        panelUtama.repaint();
        FPembayaran spl = new FPembayaran();
        
        //size screen
        Dimension layarUtama = this.getSize();
        Dimension layarTbh = spl.getSize();
        
        //simpan posisi frame ke tengah
        spl.setLocation(layarUtama.width/2-layarTbh.width/2,layarUtama.height/2-layarTbh.height/2);
        
        panelUtama.add(spl);
        spl.setVisible(true);
    }//GEN-LAST:event_menuTambahPembayaranActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem dataBarang;
    private javax.swing.JMenuItem dataPembayaran;
    private javax.swing.JMenuItem dataPembeli;
    private javax.swing.JMenuItem dataSupplier;
    private javax.swing.JMenuItem dataTransaksi;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenu menuSupplier;
    private javax.swing.JMenuItem menuTambahBarang;
    private javax.swing.JMenuItem menuTambahPembayaran;
    private javax.swing.JMenuItem menuTambahPembeli;
    private javax.swing.JMenuItem menuTambahSupplier;
    private javax.swing.JMenuItem menuTambahTransaksi;
    private javax.swing.JDesktopPane panelUtama;
    // End of variables declaration//GEN-END:variables
}
