
import Form.FTambahBarang;
import Form.FTambahPembeli;
import Form.FTambahSupplier;
import data.FLihatBarang;
import java.awt.Dimension;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuTambahBarang = new javax.swing.JMenuItem();
        menuTambahPembeli = new javax.swing.JMenuItem();
        menuTambahSupplier = new javax.swing.JMenuItem();
        menuTambahTransaksi = new javax.swing.JMenuItem();
        menuTambahPembayaran = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        dataBarang = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu2.setText("Form");

        menuTambahBarang.setText("Tambah Data Barang");
        menuTambahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTambahBarangActionPerformed(evt);
            }
        });
        jMenu2.add(menuTambahBarang);

        menuTambahPembeli.setText("Tambah Data Pembeli");
        menuTambahPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTambahPembeliActionPerformed(evt);
            }
        });
        jMenu2.add(menuTambahPembeli);

        menuTambahSupplier.setText("Tambah Data Supplier");
        menuTambahSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTambahSupplierActionPerformed(evt);
            }
        });
        jMenu2.add(menuTambahSupplier);

        menuTambahTransaksi.setText("Tambah Data Transaksi");
        jMenu2.add(menuTambahTransaksi);

        menuTambahPembayaran.setText("Tambah Data Pembayaran");
        jMenu2.add(menuTambahPembayaran);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Data");

        dataBarang.setText("Barang");
        dataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataBarangActionPerformed(evt);
            }
        });
        jMenu1.add(dataBarang);
        jMenu1.add(jSeparator2);

        jMenuItem6.setText("Pembeli");
        jMenu1.add(jMenuItem6);
        jMenu1.add(jSeparator1);

        jMenuItem4.setText("Transaksi");
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator3);

        jMenuItem3.setText("Pembayaran");
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator4);

        jMenuItem5.setText("Supplier");
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("About");

        jMenuItem2.setText("Made with <3 by Mart Team Provis 6");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuTambahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTambahBarangActionPerformed
        // TODO add your handling code here:
        panelUtama.removeAll();
        panelUtama.repaint();
        FTambahBarang tbh = new FTambahBarang();
        
        //size screen
        Dimension layarUtama = this.getSize();
        Dimension layarTbh = tbh.getSize();
        
        //simpan posisi frame ke tengah
        tbh.setLocation(layarUtama.width/2-layarTbh.width/2,layarUtama.height/2-layarTbh.height/2);
        
        panelUtama.add(tbh);
        tbh.setVisible(true);
    }//GEN-LAST:event_menuTambahBarangActionPerformed

    private void dataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataBarangActionPerformed
        // TODO add your handling code here:
        panelUtama.removeAll();
        panelUtama.repaint();
        FLihatBarang brg = new FLihatBarang();
        
        //size screen
        Dimension layarUtama = this.getSize();
        Dimension layarTbh = brg.getSize();
        
        //simpan posisi frame ke tengah
        brg.setLocation(layarUtama.width/2-layarTbh.width/2,layarUtama.height/2-layarTbh.height/2);
        
        panelUtama.add(brg);
        brg.setVisible(true);
    }//GEN-LAST:event_dataBarangActionPerformed

    private void menuTambahPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTambahPembeliActionPerformed
        // TODO add your handling code here:
        panelUtama.removeAll();
        panelUtama.repaint();
        FTambahPembeli pbl = new FTambahPembeli();
        
        //size screen
        Dimension layarUtama = this.getSize();
        Dimension layarTbh = pbl.getSize();
        
        //simpan posisi frame ke tengah
        pbl.setLocation(layarUtama.width/2-layarTbh.width/2,layarUtama.height/2-layarTbh.height/2);
        
        panelUtama.add(pbl);
        pbl.setVisible(true);
    }//GEN-LAST:event_menuTambahPembeliActionPerformed

    private void menuTambahSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTambahSupplierActionPerformed
        // TODO add your handling code here:
        panelUtama.removeAll();
        panelUtama.repaint();
        FTambahSupplier spl = new FTambahSupplier();
        
        //size screen
        Dimension layarUtama = this.getSize();
        Dimension layarTbh = spl.getSize();
        
        //simpan posisi frame ke tengah
        spl.setLocation(layarUtama.width/2-layarTbh.width/2,layarUtama.height/2-layarTbh.height/2);
        
        panelUtama.add(spl);
        spl.setVisible(true);
    }//GEN-LAST:event_menuTambahSupplierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem dataBarang;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuItem menuTambahBarang;
    private javax.swing.JMenuItem menuTambahPembayaran;
    private javax.swing.JMenuItem menuTambahPembeli;
    private javax.swing.JMenuItem menuTambahSupplier;
    private javax.swing.JMenuItem menuTambahTransaksi;
    private javax.swing.JDesktopPane panelUtama;
    // End of variables declaration//GEN-END:variables
}
