/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package data;

import db.Config;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class FLihatPembeli extends javax.swing.JInternalFrame {

    /**
     * Creates new form FLihatBarang
     */
    public FLihatPembeli() {
        initComponents();
        tabel();
    }

private void tabel(){ 
    DefaultTableModel t= new DefaultTableModel();
    t.addColumn("ID Pembeli");
    t.addColumn("Nama Pembeli");   
    t.addColumn("Jenis kelamin");
    t.addColumn("No Telepon");
    t.addColumn("Alamat");
     tabelPembeli.setModel(t); 
 
 try { 
    //conect
    Connection conn = (Connection) Config.configDB();
            
    //state
    Statement st = conn.createStatement();
    
    //query sql
    String sql = "select * from pembeli"; 
    //exce
    ResultSet rs = st.executeQuery(sql);
     while (rs.next()) { 
        t.addRow(new Object[]{ 
            rs.getString("id_pembeli"),
            rs.getString("nama_pembeli"),   
            rs.getString("jk"), 
            rs.getString("no_telp"), 
            rs.getString("alamat")
        }); 
    }
     rs.close();
    st.close();
    }catch (Exception e) { 
    JOptionPane.showMessageDialog(null,"Error : "+e); 
    } 
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPembeli = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("LIHAT PEMBELI");

        tabelPembeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 2", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(tabelPembeli);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelPembeli;
    // End of variables declaration//GEN-END:variables
}
